### ISSUE TITLE
add a link to the instructions file to the readme

### ISSUE THREAD

**Issue by blue-dreaming** [KristalC/Easy-Fanfic-Library#2]
Would it be possible to add a link to the instructions file to the readme? I know that the list of files is also visible on the page, but it's a little confusing for anyone unfamiliar with github etc. (I've occionally been tripped up myself.) as the eye is naturally drawn to the text and skips over the list of files.

**Comment by KristalC** [comment]
That was a good idea, thank you. That should be updated now. Apologies for the delay.
